<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.bmw-carit</groupId>
	<artifactId>barefoot</artifactId>
	<version>3.3.0</version>

    <build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.14.0</version>
				<configuration>
					<source>21</source>
					<target>21</target>
				</configuration>
			</plugin>
			<plugin>
				<groupId>com.google.cloud.tools</groupId>
				<artifactId>jib-maven-plugin</artifactId>
				<version>3.3.1</version>
			</plugin>
		</plugins>
    </build>

	<dependencies>
		<dependency>
			<groupId>org.apache.logging.log4j</groupId>
			<artifactId>log4j-slf4j2-impl</artifactId>
		</dependency>
		<!-- https://github.com/dschrade/geometry-api-java -->
		<dependency>
			<groupId>com.esri.geometry</groupId>
			<artifactId>esri-geometry-api-strict</artifactId>
		</dependency>
		<dependency>
			<groupId>org.json</groupId>
			<artifactId>json</artifactId>
		</dependency>
		<!-- https://github.com/dschrade/geographiclib-java -->
		<dependency>
			<groupId>net.sf.geographiclib</groupId>
			<artifactId>GeographicLib-Java-strict</artifactId>
		</dependency>
	</dependencies>
	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.apache.logging.log4j</groupId>
				<artifactId>log4j-slf4j2-impl</artifactId>
				<version>2.25.0</version>
			</dependency>
			<dependency>
				<groupId>junit</groupId>
				<artifactId>junit</artifactId>
				<version>4.13.2</version>
			</dependency>
			<dependency>
				<groupId>org.json</groupId>
				<artifactId>json</artifactId>
				<version>20250517</version>
			</dependency>
			<dependency>
				<groupId>com.esri.geometry</groupId>
				<artifactId>esri-geometry-api-strict</artifactId>
				<version>2.3.0</version>
			</dependency>
			<dependency>
				<groupId>net.sf.geographiclib</groupId>
				<artifactId>GeographicLib-Java-strict</artifactId>
				<version>2.1.0</version>
			</dependency>
		</dependencies>
	</dependencyManagement>
</project>
